# Generated by Django 3.1 on 2020-09-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('employer_address', models.CharField(blank=True, max_length=100)),
                ('paid_type', models.CharField(blank=True, choices=[('R', 'Range'), ('S', 'Starting at'), ('U', 'Up to'), ('E', 'Exact rate')], max_length=1)),
                ('range_pay_lower', models.FloatField(blank=True)),
                ('range_pay_higher', models.FloatField(blank=True)),
                ('range_pay_kind', models.CharField(blank=True, choices=[('PH', 'per hour'), ('PD', 'per day'), ('PW', 'per week'), ('PM', 'per month'), ('PY', 'per year')], max_length=30)),
                ('range_pay_starting', models.FloatField(blank=True)),
                ('range_pay_upto', models.FloatField(blank=True)),
                ('range_pay_exact', models.FloatField(blank=True)),
                ('hire_count', models.CharField(blank=True, choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6'), ('SEVEN', '7'), ('EIGHT', '8'), ('NIGHT', '9'), ('TEN', '10'), ('MTEN', '10+'), ('ONGOING', 'I have an ongoing need to fill this role')], max_length=10)),
                ('deadline', models.CharField(blank=True, choices=[('1:3:D', '1 to 3 days'), ('3:7:D', '3 to 7 days'), ('1:2:W', '1 to 2 weeks'), ('2:4:W', '1 to 3 weeks'), ('4::W', '1 to 3 days')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('receive_method', models.CharField(choices=[('P', 'Phone'), ('E', 'Email')], default='E', max_length=1)),
                ('receive_email', models.CharField(blank=True, max_length=100)),
                ('receive_phone', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Publish'), ('F', 'Fake'), ('E', 'Ended')], default='D', max_length=1)),
                ('availability', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.availabilities')),
                ('benefit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.benefits')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobkinds')),
                ('supplement', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.supplementalpay')),
            ],
        ),
    ]
