# Generated by Django 3.1 on 2020-09-30 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_jobs_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='availability',
        ),
        migrations.AddField(
            model_name='jobs',
            name='availability',
            field=models.ManyToManyField(to='jobs.Availabilities'),
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='benefit',
        ),
        migrations.AddField(
            model_name='jobs',
            name='benefit',
            field=models.ManyToManyField(to='jobs.Benefits'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.CharField(blank=True, choices=[('1:3:D', '1 to 3 days'), ('3:7:D', '3 to 7 days'), ('1:2:W', '1 to 2 weeks'), ('2:4:W', '2 to 4 weeks'), ('4::W', '1 to 3 days')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='hire_count',
            field=models.CharField(blank=True, choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6'), ('SEVEN', '7'), ('EIGHT', '8'), ('NIGHT', '9'), ('TEN', '10'), ('MTEN', '10+'), ('ONGOING', 'I have an ongoing need to fill this role')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobkinds'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='supplement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.supplementalpay'),
        ),
    ]
