# Generated by Django 3.1 on 2020-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201001_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='receive_email',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='receive_phone',
        ),
        migrations.AddField(
            model_name='jobs',
            name='first_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobs',
            name='second_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='third_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
