# Generated by Django 3.1 on 2020-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201001_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='range_pay_kind',
        ),
        migrations.AddField(
            model_name='jobs',
            name='paid_kind',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='first_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='hire_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='paid_type',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='receive_method',
            field=models.CharField(default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='second_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='third_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
