# Generated by Django 3.1 on 2020-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201002_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='range_pay_exact',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='range_pay_higher',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='range_pay_lower',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='range_pay_starting',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='range_pay_upto',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
