# Generated by Django 3.1 on 2020-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201002_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='inform_method',
            field=models.CharField(choices=[('D', 'Daily'), ('I', 'Individually')], default='D', max_length=10),
        ),
    ]
