# Generated by Django 3.1 on 2020-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobs_inform_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='inform_method',
            field=models.CharField(choices=[('D', 'Daily'), ('I', 'Individually')], default='D', max_length=1),
        ),
    ]
